#!/usr/bin/env php
<?php

/**
 * Laika PHP MVC Framework
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP MVC Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

// Define The Base Path
define('APP_PATH', __DIR__);

// Use Console
use Laika\Core\Console\Kernel;

// Check LAIKA Working From CLI
if (strtolower(PHP_SAPI) !== 'cli') {
    die("WARNING: Require Terminal To Run Laika CLI!\n");
}

$app_file = APP_PATH.'/lf-boot/app.php';

// Check LAIKA is in Right Directory
if (!is_file($app_file)) {
    die("WARNING: Laika is in Wrong Path!\n");
}
require_once($app_file);


$kernel = new Kernel();
$kernel->run($argv);