#!/usr/bin/env php
<?php
use Laika\Cli\Application;

// Define App Path & Directory Separator
defined('APP_PATH') || define('APP_PATH', __DIR__);
defined('DS') || define('DS', DIRECTORY_SEPARATOR);

require realpath(APP_PATH . '/vendor/autoload.php');

$app = new Application(APP_PATH);

exit($app->run($argv));
