<?php
/**
 * Laika PHP Micro Framework
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP Micro Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

########################################################################################
############################# PLEASE DO NOT EDIT THIS FILE #############################
########################################################################################

declare(strict_types=1);

use Laika\Service\Infra;

#################################################################
// ---------------------APP PATH CONSTANT--------------------- //
#################################################################
defined('APP_PATH') || define('APP_PATH', dirname(__DIR__));

################################################################
// ----------------------- INCLUDES ------------------------- //
################################################################
require_once APP_PATH . '/lf-inc/const.php';

// ---------------------------------------------------------- //

################################################################
// ----------------------- AUTOLOADER ----------------------- //
################################################################
require_once APP_PATH . '/vendor/autoload.php';
// ---------------------------------------------------------- //

################################################################
// ----------------- LOAD FUNCTIONS & HOOKS ----------------- //
################################################################
foreach (Infra::getFunctionFiles() as $file) require_once $file;
foreach (Infra::getHookFiles() as $file) require_once $file;
