<?php
/**
 * Laika PHP Micro Framework
 * Author: Showket Ahmed
 * Email: riyadhtayf@gmail.com
 * License: MIT
 * This file is part of the Laika PHP Micro Framework.
 * For the full copyright and license information, please view the LICENSE file that was distributed with this source code.
 */

########################################################################################
############################# PLEASE DO NOT EDIT THIS FILE #############################
########################################################################################

declare(strict_types=1);

use Laika\Engine\Services\Infra;
use Laika\Engine\Route\Dispatcher;

#################################################################
// --------------------- DEFINE CONSTANT --------------------- //
#################################################################
defined('APP_PATH') || define('APP_PATH', dirname(__DIR__));
defined('DS') || define('DS', DIRECTORY_SEPARATOR);

################################################################
// ----------------------- INCLUDES ------------------------- //
################################################################
require_once APP_PATH . '/lf-inc/const.php';

// ---------------------------------------------------------- //

################################################################
// ----------------------- AUTOLOADER ----------------------- //
################################################################
require_once APP_PATH . '/vendor/autoload.php';
// ---------------------------------------------------------- //

################################################################
// --------------------- STATIC FILES ----------------------- //
################################################################
// A static file needs none of what follows, so it is answered here rather
// than after the function and hook files have been discovered and loaded.
// The relay container it does need was built by the autoloader above.
//
// exit, not return: index.php requires this file, so returning would hand
// control back and dispatch the same request a second time.
//
// The CLI guard matters -- bin/laika and the queue worker require this file
// too, and neither has a request to answer.
if (PHP_SAPI !== 'cli' && Dispatcher::dispatchAsset()) {
    exit;
}
// ---------------------------------------------------------- //

################################################################
// ----------------- LOAD FUNCTIONS & HOOKS ----------------- //
################################################################
foreach (Infra::getFunctionFiles() as $file) require_once $file;
foreach (Infra::getHookFiles() as $file) require_once $file;
